[package]
name = "wlsplit"
version = "0.1.0"
authors = ["Tobias Langendorf <junglerobba@jngl.one>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
livesplit-core = "*"
clap = "*"
termion = "*"
tui = { version = "0.10.0", features = ["crossterm"], default-features = false }
rand = "*"
crossterm = "*"
